### ISSUE TITLE
Won’t show

### ISSUE THREAD

**Issue by mxoongal** [derfl007/BnBHiddenFeatures#1]
I tried to run this mod , but I can’t seem to get it to work I tried everything but it’s not working

**Comment by derfl007** [comment]
Hey, are you sure you installed everything correctly? 
The game folder should look like this:
![image](https://user-images.githubusercontent.com/20611154/184497994-37425529-4741-46e2-9b83-3a55938d2833.png)

If you did all that correctly and it still doesn't work, please do the following: Go to <Game Folder>/BepInEx/config and open the BepInEx.cfg file with any text editor (preferably Notepad++ or VSCode if you have it. If not, windows notepad is fine) 
In that file you'll want to look for `[Logging.Console]` (line 43) and change `Enabled = false` to `Enabled = true`  
That will open a console when you start the game, see if you can see any error messages in there and if you do leave a comment with a screenshot here, thank you!

**Comment by mxoongal** [comment]
Do I put it in this location? 

(D:)> Steam Games > steamapps>common> Bear and Breakfast

the location I originally put it in the first time was 

(D:)>Steam Games > steamapps>common>BearAndBreakfast_Data 

which I assume is why it wasn’t working

**Comment by derfl007** [comment]
Yeah exactly, that's where you need to put it, then it should work!

I'm closing the issue, but if you have any more issues feel free to comment.
